INSERT INTO LOCALIZACAO (MOTO_ID, LATITUDE, LONGITUDE, DATA_HORA)
SELECT M.ID, -23.5620, -46.6544, SYSTIMESTAMP
FROM MOTO M
WHERE M.PLACA = 'ABC1D23';

INSERT INTO LOCALIZACAO (MOTO_ID, LATITUDE, LONGITUDE, DATA_HORA)
SELECT M.ID, -23.5651, -46.6512, SYSTIMESTAMP
FROM MOTO M
WHERE M.PLACA = 'XYZ9K88';
