CREATE TABLE USERS (
                       USERNAME VARCHAR2(50) PRIMARY KEY,
                       PASSWORD VARCHAR2(100) NOT NULL,
                       ENABLED  NUMBER(1)     NOT NULL CHECK (ENABLED IN (0,1))
);

CREATE TABLE AUTHORITIES (
                             USERNAME  VARCHAR2(50) NOT NULL,
                             AUTHORITY VARCHAR2(50) NOT NULL,
                             CONSTRAINT FK_AUTH_USERS FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME_AUTHORITY ON AUTHORITIES (USERNAME, AUTHORITY);
